// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8LGcn0y1TKUJQWRw4kgWD05Yl4dp42hY',
    appId: '1:908552924445:web:36cf7342930343870bc5f4',
    messagingSenderId: '908552924445',
    projectId: 'notes-app-153f4',
    authDomain: 'notes-app-153f4.firebaseapp.com',
    storageBucket: 'notes-app-153f4.firebasestorage.app',
    measurementId: 'G-90BEYBPQ0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbvqcN10FqdZJIcgTncAShKVEIKqooRms',
    appId: '1:908552924445:android:f2dbd497da50518a0bc5f4',
    messagingSenderId: '908552924445',
    projectId: 'notes-app-153f4',
    storageBucket: 'notes-app-153f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8B4xa1KSIY7OpawSSF0Nq_yfV2MYN9go',
    appId: '1:908552924445:ios:052405d9f9d2cce30bc5f4',
    messagingSenderId: '908552924445',
    projectId: 'notes-app-153f4',
    storageBucket: 'notes-app-153f4.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8B4xa1KSIY7OpawSSF0Nq_yfV2MYN9go',
    appId: '1:908552924445:ios:052405d9f9d2cce30bc5f4',
    messagingSenderId: '908552924445',
    projectId: 'notes-app-153f4',
    storageBucket: 'notes-app-153f4.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8LGcn0y1TKUJQWRw4kgWD05Yl4dp42hY',
    appId: '1:908552924445:web:1aeb1024fc478ccf0bc5f4',
    messagingSenderId: '908552924445',
    projectId: 'notes-app-153f4',
    authDomain: 'notes-app-153f4.firebaseapp.com',
    storageBucket: 'notes-app-153f4.firebasestorage.app',
    measurementId: 'G-6FCEJS5RT8',
  );
}
